version: '3.8'

services:
  mysql:
    container_name: my-mysql
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
  integration-test:
    container_name: integration-test
    image: integration-test:latest
    ports:
      - 12110:12110
