version: 2.1
jobs:
  tests:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run:
          name: Start MySQL container
          command: docker-compose up -d mysql

      # Add your build and test steps here

workflows:
  version: 2
  integration-tests:
    jobs:
      - tests
