version: 2.1
executors:
  go-executor:
    docker:
      - image: circleci/golang:1.17
    environment:
      DOCKER_COMPOSE_VERSION: 1.29.2
jobs:
  tests:
    working_directory: /home/circleci/app
    #executor: go-executor
    docker:
      - image: circleci/golang:1.17
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.12
      - run:
          name: Install dependencies
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.27.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Start MySQL container
          command: |
            docker-compose up -d mysql
            sleep 5
      - run:
          name: Build test container
          command: docker build -t my-gotest:latest .
      - run:
          name: Run test
          command: |
            docker run -t --network app_default my-gotest:latest --name integration-test
      - run:
          name: Prepare test results
          command: |
            make install-junitor
            mkdir test-results
            docker cp integration-test:/app/test-results - | go-junit-report > test-results/report.xml
      - store_artifacts:
          path: test-results
      - store_test_results:
          path: test-results

      # Add your build and test steps here

workflows:
  version: 2
  integration-tests:
    jobs:
      - tests
