version: 2.1
jobs:
  tests:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout

      - run:
          name: Start database
          command: |
            docker run --name my-mysql --network my-network -e MYSQL_ROOT_PASSWORD=$(DB_PASSWORD) -p 3306:3306 -d mysql:latest

workflows:
  version: 2
  integration-tests:
    jobs:
      - tests
