version: 2.1
executors:
  go-executor:
    docker:
      - image: circleci/golang:1.17
    environment:
      DOCKER_COMPOSE_VERSION: 1.29.2
jobs:
  tests:
    working_directory: /home/circleci/app
    #executor: go-executor
    docker:
      - image: circleci/golang:1.17
    steps:
      - run:
          name: whoam
          command: |
            echo $USER
            chown -R $USER:$USER /home/circleci/app
            git init /home/circleci/app
      #- checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.12
      - run:
          name: Install dependencies
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Start MySQL container
          command: ls
      - run:
          name: Run tests
          command: go test ./... -v --race

      # Add your build and test steps here

workflows:
  version: 2
  integration-tests:
    jobs:
      - tests
