version: 2.1
executors:
  go-executor:
    docker:
      - image: circleci/golang:1.17
    environment:
      DOCKER_COMPOSE_VERSION: 1.29.2
jobs:
  tests:
    working_directory: /home/circleci/app
    #executor: go-executor
    docker:
      - image: circleci/golang:1.17
    steps:
      - run:
          name: whoam
          command: |
            echo $USER
            chown -R $USER:$USER /home/circleci/app
            git init /home/circleci/app
      #- checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.12
      - run:
          name: Install dependencies
          command: |
            apk update && apk upgrade && apk add curl
            sudo chown -R $USER:$USER /usr/local/bin
            curl -L "https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose  
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Start MySQL container
          command: docker-compose up -d mysql
      - run:
          name: Run tests
          command: go test ./... -v --race

      # Add your build and test steps here

workflows:
  version: 2
  integration-tests:
    jobs:
      - tests
